export const typography = {
  letterSpacings: {
    tighter: "-0.05em",
    tight: "-0.025em",
    normal: "0",
    wide: "0.025em",
    wider: "0.05em",
    widest: "0.1em",
  },
  lineHeights: {
    normal: "normal",
    none: 1,
    shorter: 1.25,
    short: 1.375,
    base: 1.5,
    tall: 1.625,
    taller: "2",
    "3": ".75rem",
    "4": "1rem",
    "5": "1.25rem",
    "6": "1.5rem",
    "7": "1.75rem",
    "8": "2rem",
    "9": "2.25rem",
    "10": "2.5rem",
  },
  fontWeights: {
    hairline: 100,
    thin: 200,
    light: 300,
    normal: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    extrabold: 800,
    black: 900,
  },
  fonts: {
    heading: `Poppins ,-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"`,
    body: `Poppins,-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"`,
    mono: `Poppins,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace`,
    montserrat: "Montserrat, Verdana,Arial, Helvetica, sans-serif",
    poppins: "Poppins, Verdana,Arial, Helvetica, sans-serif",
    sosieone: "Sonsie One, Verdana,Arial, Helvetica, sans-serif",
    saira: "Saira, Verdana,Arial, Helvetica, sans-serif",
  },
  fontSize: {
    mono: "2px",
    s: "4px",
    xss: "6px",
    xs: "10px",
    xxs: "8px",
    sm: "12px",
    md: "14px",
    lg: "16px",
    xl: "18px",
    xxl: "24px",
    xxxl: "32px",
    xxxxl: "40px",
  },
};
